services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /opt/qbittorrent/config:/config
      - /mnt/eagle1/downloads:/downloads
      - /mnt/eagle1:/data
    ports:
      - 8080:8080
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
